//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Students = new HashSet<Student>();
        }
    
        public string Name { get; set; }
        public string Grade { get; set; }
        public int No { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp
    {
        public Exp()
        {
            this.ExpParas = new HashSet<ExpPara>();
            this.ExpValues = new HashSet<ExpValue>();
            this.BlackGroups = new HashSet<Group>();
            this.WhiteGroups = new HashSet<Group>();
        }
    
        public int TypeNo { get; set; }
        public int No { get; set; }
        public string Name { get; set; }
        public short SubmitMode { get; set; }
        public short ReadMode { get; set; }
        public string Des { get; set; }
    
        public virtual ExpType ExpType { get; set; }
        public virtual ICollection<ExpPara> ExpParas { get; set; }
        public virtual ICollection<ExpValue> ExpValues { get; set; }
        public virtual ICollection<Group> BlackGroups { get; set; }
        public virtual ICollection<Group> WhiteGroups { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpPara
    {
        public int No { get; set; }
        public int ExpNo { get; set; }
        public short ValueType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Exp Exp { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpType
    {
        public ExpType()
        {
            this.Exps = new HashSet<Exp>();
        }
    
        public string Name { get; set; }
        public int No { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<Exp> Exps { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpValue
    {
        public string Value { get; set; }
        public int ExpNo { get; set; }
        public int StudentNo { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Seq { get; set; }
        public int No { get; set; }
    
        public virtual Exp Exp { get; set; }
        public virtual Student Student { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
            this.BlackExps = new HashSet<Exp>();
            this.WhiteExps = new HashSet<Exp>();
        }
    
        public int No { get; set; }
        public string GroupName { get; set; }
        public short Type { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Exp> BlackExps { get; set; }
        public virtual ICollection<Exp> WhiteExps { get; set; }
    }
}
namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.ExpValues = new HashSet<ExpValue>();
            this.Groups = new HashSet<Group>();
        }
    
        public int No { get; set; }
        public string StudentName { get; set; }
        public string UserName { get; set; }
        public short Role { get; set; }
        public int Exp { get; set; }
        public Nullable<int> ClassNo { get; set; }
    
        public virtual ICollection<ExpValue> ExpValues { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual Class Class { get; set; }
    }
}
