//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Comments = new HashSet<Comment>();
            this.PublicEvents = new HashSet<PublicEvent>();
        }
    
        public string UserName { get; set; }
        public int No { get; set; }
        public string RealName { get; set; }
        public string Grade { get; set; }
        public short Role { get; set; }
        public short EventLimit { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<PublicEvent> PublicEvents { get; set; }
    }
}
namespace Msg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.PublicEvents = new HashSet<PublicEvent>();
        }
    
        public int No { get; set; }
        public string Name { get; set; }
        public bool Enable { get; set; }
        public short Priority { get; set; }
    
        public virtual ICollection<PublicEvent> PublicEvents { get; set; }
    }
}
namespace Msg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int AuthorNo { get; set; }
        public int No { get; set; }
        public System.DateTime SetDate { get; set; }
        public int EventNo { get; set; }
        public string Color { get; set; }
        public short Priority { get; set; }
        public bool Deleted { get; set; }
        public string Body { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual PublicEvent PublicEvent { get; set; }
    }
}
namespace Msg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicEvent
    {
        public PublicEvent()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string Title { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string ImgUrl { get; set; }
        public bool Enable { get; set; }
        public string Text { get; set; }
        public int No { get; set; }
        public short Priority { get; set; }
        public string MTitle { get; set; }
        public int CategoryNo { get; set; }
        public string AudioUrl { get; set; }
        public int AuthorNo { get; set; }
        public string AuthorName { get; set; }
        public System.DateTime SetTime { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
